{{- if .Values.kubesec.enabled -}}
{{- $_ := set . "Label" "metrics" }}
{{- $_ := set . "Config" .Values.prometheus }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  {{- include "metadata" .Label }}
spec:
  {{ include "cronjob-spec" . | nindent 2 | trim }}
  jobTemplate:
    spec:
      {{ include "job-spec" . | nindent 6 | trim }}
      template:
        spec:
          {{ include "job-template-spec" . | indent 10 | trim }}
          containers:
          - {{ include "container-spec" . | indent 12 | trim }}
            command:
            - prometheus-collector
            {{ include "security-context" . | indent 12 | trim }}
          {{ include "uploaderContainer" . | indent 10 | trim }}
{{- end -}}
