# For testing, make sure to install the vpa and metrics-server as sub-charts
vpa:
  enabled: true

metrics-server:
  enabled: true
  extraArgs:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP

controller:
  flags:
    on-by-default: true
    exclude-namespaces: kube-system
  deployment:
    additionalLabels:
      test: value
    podAnnotations:
      foo: bar
  rbac:
    extraRules:
      - apiGroups:
          - "batch"
        resources:
          - "*"
        verbs:
          - "get"
          - "list"
          - "watch"
    extraClusterRoleBindings:
      - view

dashboard:
  basePath: goldilocks
  ingress:
    enabled: true
    hosts:
      - host: goldilocks.example.local
        paths:
          - path: /
            type: ImplementationSpecific
  replicaCount: 2
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: alertmanager
  deployment:
    additionalLabels:
      test: value
