---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
     - id: check-json
     - id: detect-private-key
     - id: trailing-whitespace
     - id: check-added-large-files
       args: ['--maxkb=150']
     - id: check-byte-order-marker
     - id: check-merge-conflict
     - id: check-symlinks
     - id: end-of-file-fixer
     - id: check-executables-have-shebangs
     # Flake8. Ignore line too long
     - id: flake8
       args: ['--ignore=E501']
     - id: no-commit-to-branch
       args: [--branch, master]
     - id: pretty-format-json
       args: ['--autofix']
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.11.0
    hooks:
      - id: forbid-binary
        exclude: >
          (?x)^(
            .+\.tgz
          )$
      - id: shellcheck
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.0.9
    hooks:
      - id: helmlint
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.4.0
    hooks:
      - id: helm-docs
        args:
          - --sort-values-order=file
