{{- if .Values.polaris.enabled -}}
# Source: polaris/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: polaris
  labels:
    app: insights-agent
data:
  config.yaml:  |
    checks:
      cpuRequestsMissing: warning
      cpuLimitsMissing: warning
      memoryRequestsMissing: warning
      memoryLimitsMissing: warning
      tagNotSpecified: danger
      pullPolicyNotAlways: ignore
      readinessProbeMissing: warning
      livenessProbeMissing: warning
      hostNetworkSet: warning
      hostPortSet: warning
      hostIPCSet: danger
      hostPIDSet: danger
      notReadOnlyRootFileSystem: warning
      privilegeEscalationAllowed: danger
      runAsRootAllowed: warning
      runAsPrivileged: danger
      dangerousCapabilities: danger
      insecureCapabilities: warning
    exemptions:
      - controllerNames:
          - dns-controller
          - nginx-ingress-controller
          - nginx-ingress-external-controller
          - datadog-datadog
          - kube-flannel-ds
          - kube2iam
          - aws-iam-authenticator
          - datadog
          - kube2iam
          - kube-proxy
        rules:
          - hostNetworkSet
      - controllerNames:
          - aws-iam-authenticator
          - aws-cluster-autoscaler
          - kube-state-metrics
          - dns-controller
          - external-dns
          - dnsmasq
          - autoscaler
          - kubernetes-dashboard
          - install-cni
          - kube2iam
          - cert-manager-cainjector
          - cert-manager-webhook
          - cert-manager
          - vpa-recommender
        rules:
          - readinessProbeMissing
          - livenessProbeMissing
      - controllerNames:
          - aws-iam-authenticator
          - nginx-ingress-controller
          - nginx-ingress-external-controller
          - nginx-ingress-default-backend
          - aws-cluster-autoscaler
          - kube-state-metrics
          - dns-controller
          - external-dns
          - kubedns
          - dnsmasq
          - autoscaler
          - tiller
          - kube2iam
          - cert-manager-webhook
          - cert-manager-cainjector
          - cert-manager
          - coredns
          - vpa-recommender
          - kube-bench
        rules:
          - runAsRootAllowed
      - controllerNames:
          - aws-iam-authenticator
          - nginx-ingress-controller
          - nginx-ingress-external-controller
          - nginx-ingress-default-backend
          - aws-cluster-autoscaler
          - kube-state-metrics
          - dns-controller
          - external-dns
          - kubedns
          - dnsmasq
          - autoscaler
          - tiller
          - kube2iam
          - cert-manager-cainjector
          - cert-manager-webhook
          - kube-proxy
          - vpa-recommender
        rules:
          - notReadOnlyRootFileSystem
      - controllerNames:
          - cert-manager
          - dns-controller
          - kubedns
          - dnsmasq
          - autoscaler
          - insights-agent-goldilocks-vpa-install
          - insights-agent-goldilocks-vpa-uninstall
          - kube-proxy
          - coredns
          - metrics-server
          - nginx-ingress-controller
          - nginx-ingress-external-controller
          - nginx-ingress-default-backend
        rules:
          - cpuRequestsMissing
          - cpuLimitsMissing
          - memoryRequestsMissing
          - memoryLimitsMissing
      - controllerNames:
          - kube2iam
          - kube-proxy
          - nginx-ingress-controller
          - nginx-ingress-external-controller
          - kube-flannel
        rules:
          - runAsPrivileged
          - privilegeEscalationAllowed
      - controllerNames:
          - kube-hunter
          - kube-bench
        rules:
          - hostPIDSet
      - controllerNames:
          - polaris
          - kube-hunter
          - goldilocks
          - trivy
          - workloads
          - insights-agent-goldilocks-vpa-install
          - insights-agent-goldilocks-vpa-uninstall
        rules:
          - notReadOnlyRootFileSystem
      - controllerNames:
          - insights-agent-goldilocks-controller
        rules:
          - livenessProbeMissing
          - readinessProbeMissing
      - controllerNames:
          - insights-agent-goldilocks-vpa-install
          - insights-agent-goldilocks-vpa-uninstall
          - kube-hunter
          - trivy
        rules:
          - runAsRootAllowed
{{- end -}}
