apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fairwinds-metrics.fullname" . }}-controller
  labels:
    app.kubernetes.io/name: {{ include "fairwinds-metrics.name" . }}
    helm.sh/chart: {{ include "fairwinds-metrics.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fairwinds-metrics.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fairwinds-metrics.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: controller
      annotations:
        {{- if .Values.controller.datadogAnnotations.enabled }}
        ad.datadoghq.com/fairwinds-metrics.check_names: |
          ["prometheus"]
        ad.datadoghq.com/fairwinds-metrics.init_configs: |
          [{}]
        ad.datadoghq.com/fairwinds-metrics.instances: |
          [
            {
              "prometheus_url": "http://%%host%%:2112/metrics",
              "namespace": "fairwinds-metrics",
              "metrics": ["fairwinds_*"],
              "max_returned_metrics": "10"
            }
          ]
        {{- end }}
    spec:
      {{- if .Values.controller.serviceAccount.create }}
      serviceAccountName: {{ include "fairwinds-metrics.fullname" . }}-controller
      {{- else }}
      serviceAccountName: {{ .Values.controller.serviceAccount.name }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /custom-metrics
            - controller
          args:
            - -v{{ .Values.controller.logVerbosity }}
            {{- if .Values.controller.enabledMetrics }}
            - --metrics
            - {{ .Values.controller.enabledMetrics }}
            {{- end }}
            - --interval
            - {{ .Values.controller.interval }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10324
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 2112
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
