{{ if hasKey .Values "resourcemetrics" }}
{{ fail "resourcemetrics has been renamed to prometheus-metrics in version 2.0. See breaking changes at https://github.com/FairwindsOps/charts/blob/master/stable/insights-agent/CHANGELOG.md" }}
{{ end }}
{{- if (index .Values "prometheus-metrics" "enabled") -}}
{{- $_ := set . "Label" "resource-metrics" }} # TODO(Barnie)- change this to `prometheus-metrics` before merging to master
{{- $_ := set . "Config" (index .Values "prometheus-metrics")}}
{{- include "cronjob" . }}
spec:
  {{ include "cronjob-spec" . | nindent 2 | trim }}
  jobTemplate:
    spec:
      {{ include "job-spec" . | nindent 6 | trim }}
      template:
        spec:
          {{ include "job-template-spec" . | indent 10 | trim }}
          containers:
          - {{ include "container-spec" . | indent 12 | trim }}
            command:
            - prometheus-collector
            env:
            - name: PROMETHEUS_ADDRESS
              value: {{ (index .Values "prometheus-metrics"  "address") | quote }}
            {{ include "security-context" . | indent 12 | trim }}
          {{ include "uploaderContainer" . | indent 10 | trim }}
{{- end -}}
