insights:
  host: http://insights-agent-test:8080
  organization: acme-co
  cluster: us-east-1
  base64token: Zm9v

goldilocks:
  enabled: false

opa:
  enabled: true

test:
  enabled: true

kubesec:
  enabled: true

polaris:
  enabled: true

pluto:
  enabled: true

nova:
  enabled: true

kubehunter:
  enabled: true

trivy:
  enabled: true
  maxScansPerRun: 2

prometheus:
  enabled: true
