insights:
  host: http://insights-agent-test:8080
  organization: acme-co
  cluster: us-east-1
  base64token: Zm9v

uploader:
  resources:
    requests:
      cpu: 50m
  env:
  - name: foo
    value: bar

# We set the CPU requests to 50m so the node doesn't run out of CPU
# TODO: why is this disabled?
goldilocks:
  enabled: false
  resources:
    requests:
      cpu: 50m

opa:
  enabled: true
  resources:
    requests:
      cpu: 50m

workloads:
  resources:
    requests:
      cpu: 50m

test:
  enabled: true

kube-bench:
  enabled: true
  resources:
    requests:
      cpu: 50m

polaris:
  enabled: true
  resources:
    requests:
      cpu: 50m

pluto:
  enabled: true
  resources:
    requests:
      cpu: 50m

nova:
  enabled: true
  resources:
    requests:
      cpu: 50m

kube-hunter:
  enabled: true
  resources:
    requests:
      cpu: 50m

trivy:
  enabled: true
  maxScansPerRun: 2
  resources:
    requests:
      cpu: 50m

prometheus-metrics:
  enabled: true
  installPrometheusServer: true
  resources:
    requests:
      cpu: 50m

prometheus:
  server:
    resources:
      requests:
        cpu: 200m

admission:
  enabled: true

aws-costs:
  enabled: false
  secretName: awscosts-secret
  awsAccessKeyId: someAccessID
  awsSecretAccessKey: someAccessKey
  region: us-east-1
  database: athena_cur_database
  table: fairwinds_insights_cur_report
  catalog: AwsDataCatalog
  tagkey: kubernetes_cluster
  tagvalue: staging.internal.reactiveops.com
  workgroup: cur_athena_workgroup

# Falco does not work well with KIND cluster
falco:
  installFalco: false
  enabled: false
  resources:
    requests:
      cpu: 50m
