insights:
  host: http://insights-agent-test:8080
  organization: acme-co
  cluster: us-east-1
  base64token: Zm9v

uploader:
  resources:
    requests:
      cpu: 50m
  env:
  - name: foo
    value: bar

# We set the CPU requests to 50m so the node doesn't run out of CPU
# TODO: why is this disabled?
goldilocks:
  enabled: false
  resources:
    requests:
      cpu: 50m

opa:
  enabled: true
  labels:
    foo: bar
  annotations:
    beez: baz
  jobLabels:
    bagel: everything
  jobAnnotations:
    flip: flop
  resources:
    requests:
      cpu: 50m

workloads:
  resources:
    requests:
      cpu: 50m

test:
  enabled: true

kube-bench:
  enabled: true
  resources:
    requests:
      cpu: 50m

polaris:
  enabled: true
  resources:
    requests:
      cpu: 50m

pluto:
  enabled: true
  resources:
    requests:
      cpu: 50m

nova:
  enabled: true
  resources:
    requests:
      cpu: 50m

kube-hunter:
  enabled: true
  resources:
    requests:
      cpu: 50m

trivy:
  enabled: true
  maxScansPerRun: 2
  resources:
    requests:
      cpu: 50m
  securityContext:
    fsGroup: 10324
  containerSecurityContext:
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    privileged: false
    runAsNonRoot: true
    runAsUser: 10324
    capabilities:
      drop:
        - ALL

prometheus-metrics:
  enabled: true
  installPrometheusServer: true
  image:
    repository: quay.io/fairwinds/prometheus-collector
    tag: "1.0"
  resources:
    requests:
      cpu: 50m

prometheus:
  server:
    resources:
      requests:
        cpu: 250m
        memory: 512Mi

admission:
  enabled: true

insights-admission:
  webhookConfig:
    failurePolicy: Ignore
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - "v1"
      operations:
      - CREATE
      - UPDATE
      - DELETE
      resources:
      - namespaces
      scope: Cluster
    - apiGroups:
      - apps
      apiVersions:
      - "v1"
      operations:
      - DELETE
      resources:
      - deployments
      - statefulsets
      scope: Cluster

awscosts:
  enabled: false
  secretName: awscosts-secret
  awsAccessKeyId: someAccessID
  awsSecretAccessKey: someAccessKey
  region: us-east-1
  database: athena_cur_database
  table: fairwinds_insights_cur_report
  catalog: AwsDataCatalog
  tagkey: kubernetes_cluster
  tagvalue: staging.internal.reactiveops.com
  workgroup: cur_athena_workgroup

cloudcosts:
  enabled: false
  secretName: cloudcosts-secret
  tagkey: kubernetes_cluster
  tagvalue: staging.internal.reactiveops.com
  aws:
    accessKeyId: someAccessID
    secretAccessKey: someAccessKey
    region: us-east-1
    database: athena_cur_database
    table: fairwinds_insights_cur_report
    catalog: AwsDataCatalog
    workgroup: cur_athena_workgroup

# Falco does not work well with KIND cluster
falco:
  installFalco: false
  enabled: false
  resources:
    requests:
      cpu: 50m

kyverno:
  enabled: false
  resources:
    requests:
      cpu: 50m

installReporter:
  additionalAnnotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded

right-sizer:
  enabled: true
  oom-detection:
    enabled: true
right-sizer-vpa:
  admissionController:
    enabled: false
  metrics-server:
    enabled: true
