# The 0.4.0 image is hosted on ECR and can not be pulled from a non-EC2 CI instance.
# For now, we use the 0.3.0 image for testing, which is more accessible.
image:
  repository: gcr.io/heptio-images/authenticator
  tag: v0.3.0
configMap:
  clusterID: my-dev-cluster.example.com
  defaultRole: arn:aws:iam::000000000000:role/KubernetesAdmin
  server:
    ec2DescribeInstancesRoleARN: arn:aws:iam::000000000000:role/DescribeInstancesRole
    mapRoles:
    - roleARN: arn:aws:iam::000000000000:role/KubernetesAdmin
      username: kubernetes-admin
      groups:
      - system:masters
    - roleARN: arn:aws:iam::000000000000:role/KubernetesNode
      username: aws:{{AccountID}}:instance:{{SessionName}}
      groups:
      - system:bootstrappers
      - aws:instances
    - roleARN: arn:aws:iam::000000000000:role/KubernetesNode
      username: system:node:{{EC2PrivateDNSName}}
      groups:
      - system:nodes
      - system:bootstrappers
    - roleARN: arn:aws:iam::000000000000:role/KubernetesAdmin
      username: admin:{{SessionName}}
      groups:
      - system:masters
    mapUsers:
    - userARN: arn:aws:iam::000000000000:user/Alice
      username: alice
      groups:
      - system:masters
    mapAccounts:
    - "012345678901"
    - "456789012345"
extraManifests:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: extra-configmap
    data:
      key: value
