job:
  debug: true
  dryRun: false  # If true, will only log candidates for removal and not remove them. Set to false for actual pruning.
pruneProfiles:
- olderThan: "3 days ago"
  helmReleaseFilter: "^fwinsights-"
  namespaceFilter: "^fwinsights-"
  maxReleasesToKeep: 40
- olderThan: "4 days ago"
  helmReleaseFilter: "^fwinsights-"
  namespaceFilter: "^fwinsights-"
  maxReleasesToKeep: 40
