apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fairwinds-insights.fullname" . }}-open-api
  labels:
    {{- include "fairwinds-insights.labels" . | nindent 4 }}
    app.kubernetes.io/component: open-api
spec:
  selector:
    matchLabels:
      {{- include "fairwinds-insights.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: open-api
  template:
    metadata:
      labels:
        {{- include "fairwinds-insights.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: open-api
    spec:
      {{- with .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      serviceAccountName: {{ include "fairwinds-insights.fullname" . }}-insights
      containers:
        - name: fairwinds-insights
          image: "{{ .Values.openApiImage.repository }}:{{ include "fairwinds-insights.openApiImageTag" . }}"
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: {{ .Values.openApi.port }}
            protocol: TCP
          env:
          - name: SWAGGER_JSON_URL
            value: {{ include "fairwinds-insights.fullname" . }}-api/v0/swagger.json
          - name: BASE_URL
            value: "/swagger"
          resources:
            {{- toYaml .Values.openApi.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            runAsUser: 101
            capabilities:
              drop:
                - ALL
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}