apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insights-admission.fullname" . }}-admission
  labels:
    app: insights-admission
    app.kubernetes.io/name: {{ include "insights-admission.fullname" . }}-admission
    {{- include "insights-admission.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      component: controller
      {{- include "insights-admission.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: insights-admission
        component: controller
        {{- include "insights-admission.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "insights-admission.serviceAccountName" . }}
      automountServiceAccountToken: false
      priorityClassName: {{ include "insights-admission.fullname" . }}-priority
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: https
            {{- if .Values.service.usePod443 }}
            {{- if or ((ne .Values.securityContext.runAsNonRoot false) (ne .Values.securityContext.runAsUser 0)) }}
              {{- fail "If using usePod443, you must specify securityContext.runAsNonRoot=false and securityContext.runAsUser=0" }}
            {{- end }}
            containerPort: 443
            {{- else }}
            containerPort: 8443
            {{- end }}
            protocol: TCP
          - name: health
            containerPort: 8081
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
          volumeMounts:
          - name: secret
            mountPath: /opt/cert/
            readOnly: true
{{ include "ssl-cert-file-volumemount-spec" . | indent 10 }}
          env:
          # This is always specified as pluto is enabled in Insights settings.
          - name: PLUTO_TARGET_VERSIONS
            value: {{ $.Values.pluto.targetVersions | default (printf "k8s=v%s.%s.0" .Capabilities.KubeVersion.Major (trimSuffix "+" .Capabilities.KubeVersion.Minor)) }}
          - name: WEBHOOK_FAILURE_POLICY
            value: {{ .Values.webhookConfig.failurePolicy }}
          {{- if .Values.service.usePod443 }}
          - name: WEBHOOK_PORT
            value: "443"
          {{- end }}
          - name: FAIRWINDS_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "insights-admission.secretName" . }}
                key: token
          - name: FAIRWINDS_ORGANIZATION
            valueFrom:
              configMapKeyRef:
                name: {{ include "insights-admission.configmapName" . }}
                key: organization
          - name: FAIRWINDS_CLUSTER
            valueFrom:
              configMapKeyRef:
                name: {{ include "insights-admission.configmapName" . }}
                key: cluster
          - name: FAIRWINDS_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: {{ include "insights-admission.configmapName" . }}
                key: host
          - name: FAIRWINDS_IGNORE_USERNAMES
            value: {{ .Values.ignoreRequestUsernames }}
          {{ include "proxy-env-spec" . | indent 10 | trim }}
          {{ include "ssl-cert-file-env-spec" . | indent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{ toYaml .Values.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: secret
        secret:
          {{- with .Values.secretName }}
          secretName: {{ . }}
          {{- else }}
          secretName: {{ include "insights-admission.fullname" . }}
{{ include "ssl-cert-file-volume-spec" . | indent 6 }}
          {{- end }}
